@echo off
echo Cleaning previous build...
del /Q sim_out wave.vcd 2>nul

echo Compiling Verilog files...
iverilog -o sim_out *.v

echo Running simulation...
vvp sim_out

echo Moving waveform output to waveforms folder...
move wave.vcd ../waveforms/wave.vcd

echo Opening GTKWave...
gtkwave ../waveforms/wave.vcd
